kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zk-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  priority_io: "high"
  group: "zk_vg"
  fg: "true"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kakfa-sc-rep2
provisioner: pxd.portworx.com
parameters:
  repl: "2"
  priority_io: "high"
  group: "kafka_vg"
  fg: "true"
---
