kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zk-sc
provisioner: pxd.portworx.com
parameters:
  repl: "1"
  priority_io: "high"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kafka-sc-rep2
provisioner: pxd.portworx.com
parameters:
  repl: "2"
  priority_io: "high"
---
